package com.example.spring_boot_web_socket.model;

import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import lombok.Data;

/**
 * Entity representing an AI-generated status record.
 * <p>
 * Stores the title and current status of an AI-generated
 * process or task in the database.
 * </p>
 */
@Data
@Entity
public class AiGeneratedStatus {

    /**
     * Unique identifier for the status record.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    protected Long id;

    /**
     * Title or name associated with the status record.
     */
    private String title;

    /**
     * Current status of the record.
     * Examples: PENDING, IN_PROGRESS, COMPLETED, FAILED.
     */
    private String status;
}
